services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  user_service:
    build: 
      context: ./UserService
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  book_service:
    build:
      context: ./BookService
      dockerfile: Dockerfile
    ports:
      - "5006:5006"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
volumes:
  db_data:
